// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMr6lV_GvfCHq6ddydjMq-kVE0AxQM0PQ',
    appId: '1:1037192182143:web:b8e3ae60a518ff9b04c24a',
    messagingSenderId: '1037192182143',
    projectId: 'tastytakout',
    authDomain: 'tastytakout.firebaseapp.com',
    storageBucket: 'tastytakout.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2LEGUBHtEkN1YMLTX8obW_z5J7UjIk8M',
    appId: '1:1037192182143:android:6c4ba21623bfb8e804c24a',
    messagingSenderId: '1037192182143',
    projectId: 'tastytakout',
    storageBucket: 'tastytakout.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-y9oxrDS6bpsACQ4roCkt7GFYuvGzhPM',
    appId: '1:1037192182143:ios:789a8d1cc7f73a5104c24a',
    messagingSenderId: '1037192182143',
    projectId: 'tastytakout',
    storageBucket: 'tastytakout.appspot.com',
    iosBundleId: 'com.example.tastytakeoutUserApp',
  );
}
